# Generated by Django 5.0.14 on 2025-10-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='local_payment_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='local_receipt_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='local_sale_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
