# Generated by Django 5.0.14 on 2025-10-05 11:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('frequent_customer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_option', models.CharField(blank=True, choices=[('pickup', 'Pick Up'), ('delivery', 'Delivery')], max_length=20, null=True)),
                ('delivery_status', models.CharField(blank=True, choices=[('pending', 'Pending Delivery'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_cost', models.DecimalField(choices=[(0, 'No Delivery (Pickup)'), (1000, 'Standard Delivery - ₦1,000'), (1500, 'Standard Delivery - ₦1,500'), (2000, 'Standard Delivery - ₦2,000'), (2500, 'Express Delivery - ₦2,500'), (3000, 'Standard Delivery - ₦3,000'), (3500, 'Priority Delivery - ₦3,500'), (4000, 'Priority Delivery - ₦4,000'), (4500, 'Priority Delivery - ₦4,500'), (5000, 'Same Day Delivery - ₦5,000'), (5500, 'Same Day Delivery - ₦5,500'), (6000, 'Same Day Delivery - ₦6,000'), (6500, 'Same Day Delivery - ₦6,500'), (7000, 'Same Day Delivery - ₦7,000'), (7500, 'Same Day Delivery - ₦7,500'), (8000, 'Same Day Delivery - ₦8,000'), (8500, 'Same Day Delivery - ₦8,500'), (9000, 'Same Day Delivery - ₦9,000')], decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_color', models.CharField(blank=True, max_length=30, null=True)),
                ('product_size', models.CharField(max_length=10)),
                ('product_category', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_products', to='store.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='LocationTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_reference', models.CharField(max_length=50, unique=True)),
                ('from_location', models.CharField(choices=[('ABUJA', 'Abuja'), ('LAGOS', 'Lagos')], max_length=10)),
                ('to_location', models.CharField(choices=[('ABUJA', 'Abuja'), ('LAGOS', 'Lagos')], max_length=10)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('pos_moniepoint', 'POS Moniepoint'), ('transfer_taj', 'Transfer Taj'), ('transfer_sterling', 'Transfer Sterling'), ('transfer_moniepoint', 'Transfer Moniepoint'), ('card', 'Card Payment'), ('mobile_money', 'Mobile Money'), ('bank_deposit', 'Bank Deposit'), ('cheque', 'Cheque')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference, receipt number, etc.', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional payment details', null=True)),
                ('processed_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='store.payment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['processed_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='store.paymentmethod')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, choices=[('black', 'Black'), ('brown', 'Brown'), ('white', 'White'), ('blue', 'Blue'), ('gray', 'Gray'), ('red', 'Red'), ('green', 'Green'), ('pink', 'Pink'), ('purple', 'Purple'), ('beige', 'Beige')], max_length=30, null=True)),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PrinterConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this printer', max_length=100)),
                ('printer_type', models.CharField(choices=[('barcode', 'Barcode Printer'), ('pos', 'POS Receipt Printer (80mm)'), ('a4', 'A4 Printer')], max_length=20)),
                ('system_printer_name', models.CharField(help_text='Exact name as it appears in system printers', max_length=255)),
                ('paper_size', models.CharField(choices=[('80mm', '80mm (POS)'), ('58mm', '58mm (Small POS)'), ('a4', 'A4 (210mm x 297mm)'), ('letter', 'Letter (216mm x 279mm)'), ('custom', 'Custom Size')], default='80mm', max_length=20)),
                ('paper_width_mm', models.IntegerField(blank=True, help_text='Paper width in mm (for custom sizes)', null=True)),
                ('paper_height_mm', models.IntegerField(blank=True, help_text='Paper height in mm (for custom sizes)', null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_print', models.BooleanField(default=False, help_text='Automatically print when generating documents')),
                ('dpi', models.IntegerField(default=203, help_text='Printer DPI (dots per inch)')),
                ('copies', models.IntegerField(default=1, help_text='Number of copies to print')),
                ('barcode_width', models.IntegerField(blank=True, default=50, help_text='Width in mm for barcode labels', null=True)),
                ('barcode_height', models.IntegerField(blank=True, default=25, help_text='Height in mm for barcode labels', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Printer Configuration',
                'verbose_name_plural': 'Printer Configurations',
                'ordering': ['printer_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrinterTaskMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(choices=[('receipt_pos', 'POS Receipt (Thermal)'), ('receipt_a4', 'Receipt (A4 Format)'), ('barcode_label', 'Barcode Label'), ('barcode_sheet', 'Barcode Sheet (A4)'), ('invoice', 'Invoice'), ('transfer_document', 'Transfer Document'), ('sales_report', 'Sales Report'), ('financial_report', 'Financial Report'), ('product_list', 'Product List'), ('customer_receipt', 'Customer Receipt'), ('delivery_note', 'Delivery Note')], help_text='The specific task or document type', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this mapping')),
                ('auto_print', models.BooleanField(default=False, help_text='Automatically print when this task is triggered')),
                ('copies', models.IntegerField(default=1, help_text='Number of copies to print')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this task mapping', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('printer', models.ForeignKey(blank=True, help_text='Printer to use for this task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.printerconfiguration')),
            ],
            options={
                'verbose_name': 'Printer Task Mapping',
                'verbose_name_plural': 'Printer Task Mappings',
                'ordering': ['task_name'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('receipt', 'Receipt'), ('barcode', 'Barcode'), ('invoice', 'Invoice'), ('report', 'Report'), ('transfer', 'Transfer Document')], max_length=20)),
                ('document_id', models.IntegerField(blank=True, help_text='ID of the document being printed', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('printing', 'Printing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('copies', models.IntegerField(default=1)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.printerconfiguration')),
            ],
            options={
                'verbose_name': 'Print Job',
                'verbose_name_plural': 'Print Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('design', models.CharField(blank=True, default='plain', max_length=50, null=True)),
                ('size', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('markup_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10)),
                ('markup', models.DecimalField(decimal_places=2, max_digits=8)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shop', models.CharField(choices=[('STORE', 'STORE')], max_length=100)),
                ('barcode_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('location', models.CharField(choices=[('ABUJA', 'Abuja'), ('LAGOS', 'Lagos')], default='ABUJA', max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['barcode_number'], name='store_produ_barcode_2206ef_idx'), models.Index(fields=['brand'], name='store_produ_brand_aa2434_idx'), models.Index(fields=['category'], name='store_produ_categor_92f296_idx'), models.Index(fields=['shop'], name='store_produ_shop_74ed4b_idx'), models.Index(fields=['color'], name='store_produ_color_4b4fa3_idx'), models.Index(fields=['design'], name='store_produ_design_ec4032_idx'), models.Index(fields=['price'], name='store_produ_price_2d55a6_idx'), models.Index(fields=['quantity'], name='store_produ_quantit_c2632f_idx'), models.Index(fields=['location'], name='store_produ_locatio_663183_idx'), models.Index(fields=['barcode_number', 'brand'], name='store_produ_barcode_72b796_idx'), models.Index(fields=['category', 'shop'], name='store_produ_categor_780a94_idx'), models.Index(fields=['category', 'color'], name='store_produ_categor_a2875f_idx'), models.Index(fields=['shop', 'location'], name='store_produ_shop_e50438_idx'), models.Index(fields=['price', 'quantity'], name='store_produ_price_43c6eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.IntegerField()),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('EDIT', 'Edit'), ('DELETE', 'Delete')], max_length=10)),
                ('reason', models.TextField()),
                ('quantity_changed', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_with_delivery', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.delivery')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='store.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_items', to='store.locationtransfer')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('md', 'Managing Director'), ('cashier', 'Cashier'), ('accountant', 'Accountant')], default='cashier', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active_staff', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
