# Generated by Django 5.0.14 on 2025-10-05 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Wrighteous Wearhouse', help_text='Your store/company name', max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='Store tagline or slogan', max_length=200, null=True)),
                ('email', models.EmailField(default='wrighteouswarehouse@gmail.com', help_text='Main contact email', max_length=254)),
                ('phone', models.CharField(default='+234 903 547 7883', help_text='Contact phone number', max_length=50)),
                ('phone_2', models.CharField(blank=True, help_text='Secondary phone number', max_length=50, null=True)),
                ('address_line_1', models.CharField(default='Suit 10/11 Amma Centre, Near AP Filling Station', help_text='Address line 1', max_length=200)),
                ('address_line_2', models.CharField(blank=True, help_text='Address line 2 (optional)', max_length=200, null=True)),
                ('city', models.CharField(default='Garki', help_text='City', max_length=100)),
                ('state', models.CharField(default='Abuja', help_text='State/Province', max_length=100)),
                ('country', models.CharField(default='Nigeria', help_text='Country', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID / Business Registration Number', max_length=100, null=True)),
                ('website', models.URLField(blank=True, help_text='Store website URL', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Store logo (recommended: 500x500px)', null=True, upload_to='store_config/logos/')),
                ('receipt_logo', models.ImageField(blank=True, help_text='Logo for receipts (recommended: 300x100px)', null=True, upload_to='store_config/receipt_logos/')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon (recommended: 32x32px)', null=True, upload_to='store_config/favicons/')),
                ('currency_symbol', models.CharField(default='₦', help_text='Currency symbol (e.g., $, €, ₦)', max_length=10)),
                ('currency_code', models.CharField(default='NGN', help_text='Currency code (e.g., USD, EUR, NGN)', max_length=3)),
                ('timezone', models.CharField(default='Africa/Lagos', help_text='Timezone (e.g., Africa/Lagos, America/New_York)', max_length=50)),
                ('date_format', models.CharField(default='%B %d, %Y', help_text='Date format (Python strftime format)', max_length=50)),
                ('receipt_header_text', models.TextField(blank=True, help_text='Custom text to show at top of receipts', null=True)),
                ('receipt_footer_text', models.TextField(default='Thank you for shopping with us!', help_text='Footer text on receipts')),
                ('show_receipt_tax_id', models.BooleanField(default=False, help_text='Show tax ID on receipts')),
                ('business_hours', models.TextField(blank=True, help_text='Business hours (e.g., Mon-Fri: 9AM-6PM)', null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this configuration active?')),
                ('deployment_name', models.CharField(default='Main Store', help_text='Deployment identifier (e.g., Main Store, Branch 1)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Configuration',
                'verbose_name_plural': 'Store Configurations',
            },
        ),
    ]
