# Generated by Django 5.0.14 on 2025-10-05 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storeconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('failed_login', 'Failed Login Attempt'), ('product_create', 'Product Created'), ('product_update', 'Product Updated'), ('product_delete', 'Product Deleted'), ('product_view', 'Product Viewed'), ('sale_create', 'Sale Created'), ('sale_cancel', 'Sale Cancelled'), ('receipt_view', 'Receipt Viewed'), ('receipt_download', 'Receipt Downloaded'), ('receipt_email', 'Receipt Emailed'), ('customer_create', 'Customer Created'), ('customer_update', 'Customer Updated'), ('customer_delete', 'Customer Deleted'), ('transfer_create', 'Transfer Created'), ('transfer_update', 'Transfer Updated'), ('quantity_update', 'Quantity Updated'), ('config_update', 'Configuration Updated'), ('printer_config', 'Printer Configuration Changed'), ('report_view', 'Report Viewed'), ('report_download', 'Report Downloaded'), ('report_email', 'Report Emailed'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('backup_create', 'Backup Created'), ('backup_restore', 'Backup Restored'), ('settings_change', 'Settings Changed'), ('other', 'Other Action')], max_length=50)),
                ('action_display', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('extra_data', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='store_activ_created_b5206d_idx'), models.Index(fields=['user', '-created_at'], name='store_activ_user_id_c25b5a_idx'), models.Index(fields=['action', '-created_at'], name='store_activ_action_6b4c22_idx')],
            },
        ),
    ]
