# Generated by Django 5.0.14 on 2025-11-19 12:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='product_name',
        ),
        migrations.AddField(
            model_name='locationtransfer',
            name='from_shop',
            field=models.CharField(blank=True, choices=[('STORE', 'Store (Shop Floor)'), ('WAREHOUSE', 'Warehouse')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='locationtransfer',
            name='internal_location',
            field=models.CharField(blank=True, choices=[('ABUJA', 'Abuja'), ('LAGOS', 'Lagos')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='locationtransfer',
            name='to_shop',
            field=models.CharField(blank=True, choices=[('STORE', 'Store (Shop Floor)'), ('WAREHOUSE', 'Warehouse')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='locationtransfer',
            name='total_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locationtransfer',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='locationtransfer',
            name='transfer_type',
            field=models.CharField(choices=[('location', 'Location Transfer'), ('internal', 'Internal Transfer')], default='location', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='loyalty_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Loyalty points discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='preorder',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='conversion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='converted_to_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preorder',
            name='created_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_preorder', to='store.invoice'),
        ),
        migrations.AddField(
            model_name='preorder',
            name='created_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_preorder', to='store.product'),
        ),
        migrations.AddField(
            model_name='preorder',
            name='design',
            field=models.CharField(blank=True, default='plain', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='location',
            field=models.CharField(blank=True, choices=[('ABUJA', 'Abuja'), ('LAGOS', 'Lagos')], default='ABUJA', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='markup',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='markup_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shop',
            field=models.CharField(blank=True, choices=[('STORE', 'Store (Shop Floor)'), ('WAREHOUSE', 'Warehouse')], default='STORE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='loyalty_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Loyalty points discount applied', max_digits=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='loyalty_points_redeemed',
            field=models.IntegerField(default=0, help_text='Number of loyalty points redeemed'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount before tax', max_digits=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total tax amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tax_details',
            field=models.TextField(blank=True, default='{}', help_text="JSON text storing tax breakdown: {'tax_name': {'rate': X, 'amount': Y, 'method': 'inclusive/exclusive'}}"),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter any custom delivery amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='locationtransfer',
            name='from_location',
            field=models.CharField(blank=True, choices=[('ABUJA', 'Abuja'), ('LAGOS', 'Lagos')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='locationtransfer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='locationtransfer',
            name='to_location',
            field=models.CharField(blank=True, choices=[('ABUJA', 'Abuja'), ('LAGOS', 'Lagos')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.CharField(choices=[('STORE', 'Store (Shop Floor)'), ('WAREHOUSE', 'Warehouse')], max_length=100),
        ),
        migrations.CreateModel(
            name='CustomerLoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points_earned', models.IntegerField(default=0, help_text='Lifetime total points earned')),
                ('total_points_redeemed', models.IntegerField(default=0, help_text='Lifetime total points redeemed')),
                ('current_balance', models.IntegerField(default=0, help_text='Current available points')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is loyalty account active?')),
                ('tier', models.CharField(default='Bronze', help_text='Membership tier (Bronze, Silver, Gold, Platinum)', max_length=50)),
                ('last_transaction_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to='store.customer')),
            ],
            options={
                'verbose_name': 'Customer Loyalty Account',
                'verbose_name_plural': 'Customer Loyalty Accounts',
                'ordering': ['-current_balance'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(default='Loyalty Rewards Program', help_text='Name of your loyalty program', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable loyalty program')),
                ('calculation_type', models.CharField(choices=[('per_transaction', 'Points per Transaction'), ('per_amount', 'Points per Amount Spent'), ('combined', 'Combined (Transaction + Amount)')], default='combined', help_text='How points are calculated', max_length=20)),
                ('points_per_transaction', models.IntegerField(default=1, help_text='Points earned per transaction (regardless of amount)')),
                ('points_per_currency_unit', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Points earned per currency unit spent (e.g., 1 point per ₦100)', max_digits=10)),
                ('currency_unit_value', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Currency amount for points calculation (e.g., ₦100)', max_digits=10)),
                ('points_to_currency_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='How much 1 point is worth in currency (e.g., 100 points = ₦100)', max_digits=10)),
                ('minimum_points_for_redemption', models.IntegerField(default=100, help_text='Minimum points required before customer can redeem')),
                ('maximum_discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Maximum percentage of transaction that can be paid with points', max_digits=5)),
                ('points_expire', models.BooleanField(default=False, help_text='Do points expire after a certain period?')),
                ('points_expiry_days', models.IntegerField(blank=True, default=365, help_text='Number of days before points expire', null=True)),
                ('send_welcome_email', models.BooleanField(default=True, help_text='Send welcome email when customer joins program')),
                ('send_points_earned_email', models.BooleanField(default=True, help_text='Send email after each transaction with points update')),
                ('send_points_redeemed_email', models.BooleanField(default=True, help_text='Send email when points are redeemed')),
                ('send_expiry_reminder_email', models.BooleanField(default=True, help_text='Send reminder email before points expire')),
                ('expiry_reminder_days', models.IntegerField(blank=True, default=30, help_text='Days before expiry to send reminder', null=True)),
                ('enable_bonus_multipliers', models.BooleanField(default=False, help_text='Enable special bonus periods or tiers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_configs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loyalty Configuration',
                'verbose_name_plural': 'Loyalty Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Payment method name (e.g., Cash, POS Moniepoint, Transfer Taj)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Internal code for the payment method (e.g., cash, pos_moniepoint)', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Display name shown to users', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this payment method')),
                ('icon_class', models.CharField(blank=True, help_text='Bootstrap icon class (e.g., bi-cash, bi-credit-card)', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Description or notes about this payment method', null=True)),
                ('requires_reference', models.BooleanField(default=False, help_text='Require reference number for this payment method')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method Configuration',
                'verbose_name_plural': 'Payment Method Configurations',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tax name (e.g., VAT, Sales Tax, GST)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code for the tax (e.g., VAT, ST, GST)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description or notes about this tax', null=True)),
                ('tax_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='Type of tax calculation', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate (percentage or fixed amount)', max_digits=5)),
                ('calculation_method', models.CharField(choices=[('inclusive', 'Inclusive (tax included in price)'), ('exclusive', 'Exclusive (tax added to price)')], default='exclusive', help_text='How tax is calculated', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this tax')),
                ('display_on_receipt', models.BooleanField(default=True, help_text='Show tax breakdown on receipts')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Configuration',
                'verbose_name_plural': 'Tax Configurations',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('design', models.CharField(blank=True, default='plain', max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('markup_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10)),
                ('markup', models.DecimalField(decimal_places=2, max_digits=8)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('location', models.CharField(choices=[('ABUJA', 'Abuja'), ('LAGOS', 'Lagos')], default='ABUJA', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_barcode', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Warehouse Inventory',
                'verbose_name_plural': 'Warehouse Inventories',
                'indexes': [models.Index(fields=['brand'], name='store_wareh_brand_f31fea_idx'), models.Index(fields=['category'], name='store_wareh_categor_8289cd_idx'), models.Index(fields=['location'], name='store_wareh_locatio_643f40_idx'), models.Index(fields=['brand', 'size', 'color', 'design', 'location'], name='store_wareh_brand_5facbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Points Earned'), ('redeemed', 'Points Redeemed'), ('expired', 'Points Expired'), ('adjusted', 'Manual Adjustment'), ('bonus', 'Bonus Points')], max_length=20)),
                ('points', models.IntegerField(help_text='Points amount (positive or negative)')),
                ('balance_after', models.IntegerField(help_text='Balance after this transaction')),
                ('description', models.TextField(blank=True)),
                ('monetary_value', models.DecimalField(blank=True, decimal_places=2, help_text='Currency value of points for this transaction', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loyalty_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store.customerloyaltyaccount')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='store.receipt')),
            ],
            options={
                'verbose_name': 'Loyalty Transaction',
                'verbose_name_plural': 'Loyalty Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['loyalty_account', '-created_at'], name='store_loyal_loyalty_88ce89_idx'), models.Index(fields=['transaction_type'], name='store_loyal_transac_5e37cc_idx'), models.Index(fields=['receipt'], name='store_loyal_receipt_724af5_idx')],
            },
        ),
    ]
