# Generated by Django 5.0.14 on 2026-02-02 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_email_alter_customer_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid so far', max_digits=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='balance_remaining',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining balance to be paid', max_digits=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Fully Paid'), ('partial', 'Partially Paid'), ('pending', 'Payment Pending')], default='paid', help_text='Payment status of this receipt', max_length=20),
        ),
        migrations.CreateModel(
            name='PartialPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid in this installment', max_digits=10)),
                ('payment_method', models.CharField(help_text='Payment method used (Cash, Card, Transfer, etc.)', max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this payment', null=True)),
                ('receipt', models.ForeignKey(help_text='The receipt this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='partial_payments', to='store.receipt')),
                ('received_by', models.ForeignKey(blank=True, help_text='Staff member who received this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partial_payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partial Payment',
                'verbose_name_plural': 'Partial Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
