# Generated by Django 5.0.14 on 2026-02-02 10:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_receipt_amount_paid_receipt_balance_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerloyaltyaccount',
            name='discount_count',
            field=models.IntegerField(default=0, help_text='Number of times discount has been applied'),
        ),
        migrations.AddField(
            model_name='customerloyaltyaccount',
            name='discount_eligible',
            field=models.BooleanField(default=False, help_text='Whether customer is currently eligible for transaction count discount'),
        ),
        migrations.AddField(
            model_name='customerloyaltyaccount',
            name='item_count',
            field=models.IntegerField(default=0, help_text='Total number of items purchased'),
        ),
        migrations.AddField(
            model_name='customerloyaltyaccount',
            name='transaction_count',
            field=models.IntegerField(default=0, help_text='Total number of transactions made'),
        ),
        migrations.AddField(
            model_name='loyaltyconfiguration',
            name='customer_type',
            field=models.CharField(choices=[('all', 'All Customers'), ('regular', 'Regular Customers'), ('vip', 'VIP Customers')], default='all', help_text='Apply this loyalty configuration to specific customer types', max_length=20),
        ),
        migrations.AddField(
            model_name='loyaltyconfiguration',
            name='item_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage per item threshold reached', max_digits=5),
        ),
        migrations.AddField(
            model_name='loyaltyconfiguration',
            name='required_item_count',
            field=models.IntegerField(default=0, help_text='Number of items purchased required for discount (for item_count_discount type)'),
        ),
        migrations.AddField(
            model_name='loyaltyconfiguration',
            name='required_transaction_count',
            field=models.IntegerField(default=0, help_text='Number of transactions required for discount (for transaction_count_discount type)'),
        ),
        migrations.AddField(
            model_name='loyaltyconfiguration',
            name='transaction_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage on next transaction after reaching count', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loyaltyconfiguration',
            name='calculation_type',
            field=models.CharField(choices=[('per_transaction', 'Points per Transaction'), ('per_amount', 'Points per Amount Spent'), ('combined', 'Combined (Transaction + Amount)'), ('transaction_count_discount', 'Transaction Count Discount'), ('item_count_discount', 'Item Count Discount')], default='combined', help_text='How points are calculated', max_length=30),
        ),
    ]
