# Generated by Django 5.0.14 on 2026-02-03 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customerloyaltyaccount_discount_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('failed_login', 'Failed Login Attempt'), ('product_create', 'Product Created'), ('product_update', 'Product Updated'), ('product_delete', 'Product Deleted'), ('product_view', 'Product Viewed'), ('sale_create', 'Sale Created'), ('sale_cancel', 'Sale Cancelled'), ('receipt_view', 'Receipt Viewed'), ('receipt_download', 'Receipt Downloaded'), ('receipt_email', 'Receipt Emailed'), ('customer_create', 'Customer Created'), ('customer_update', 'Customer Updated'), ('customer_delete', 'Customer Deleted'), ('transfer_create', 'Transfer Created'), ('transfer_update', 'Transfer Updated'), ('quantity_update', 'Quantity Updated'), ('config_update', 'Configuration Updated'), ('printer_config', 'Printer Configuration Changed'), ('report_view', 'Report Viewed'), ('report_download', 'Report Downloaded'), ('report_email', 'Report Emailed'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('backup_create', 'Backup Created'), ('backup_restore', 'Backup Restored'), ('settings_change', 'Settings Changed'), ('return_create', 'Return Created'), ('return_approve', 'Return Approved'), ('return_reject', 'Return Rejected'), ('return_complete', 'Return Completed'), ('return_cancel', 'Return Cancelled'), ('other', 'Other Action')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='action',
            field=models.CharField(choices=[('EDIT', 'Edit'), ('DELETE', 'Delete'), ('RETURN', 'Return')], max_length=10),
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('restocking_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('return_reason', models.CharField(choices=[('defective', 'Defective/Damaged'), ('wrong_item', 'Wrong Item'), ('wrong_size', 'Wrong Size'), ('changed_mind', 'Changed Mind'), ('not_as_described', 'Not as Described'), ('other', 'Other')], default='other', max_length=50)),
                ('reason_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('refund_type', models.CharField(blank=True, choices=[('cash', 'Cash Refund'), ('store_credit', 'Store Credit')], max_length=20, null=True)),
                ('refund_method', models.CharField(blank=True, max_length=50, null=True)),
                ('refund_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('refunded_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_approved', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_processed', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='store.receipt')),
            ],
            options={
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField()),
                ('quantity_returned', models.IntegerField()),
                ('original_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('original_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_condition', models.CharField(choices=[('new', 'Like New'), ('good', 'Good Condition'), ('fair', 'Fair Condition'), ('damaged', 'Damaged'), ('defective', 'Defective')], default='new', max_length=20)),
                ('restock_to_inventory', models.BooleanField(default=True)),
                ('restocked', models.BooleanField(default=False)),
                ('restocked_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='store.sale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('return_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='store.return')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StoreCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_credits', to='store.customer')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('return_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.return')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='StoreCreditUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_date', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.receipt')),
                ('store_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='store.storecredit')),
                ('used_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_date'],
            },
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['-return_date'], name='store_retur_return__019f51_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['receipt'], name='store_retur_receipt_2bea74_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['customer'], name='store_retur_custome_72f0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['status'], name='store_retur_status_6e71f6_idx'),
        ),
        migrations.AddIndex(
            model_name='storecredit',
            index=models.Index(fields=['customer', 'is_active'], name='store_store_custome_6d8054_idx'),
        ),
        migrations.AddIndex(
            model_name='storecredit',
            index=models.Index(fields=['-issued_date'], name='store_store_issued__bed6f8_idx'),
        ),
    ]
