# Generated by Django 5.0.14 on 2026-02-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_activitylog_action_alter_producthistory_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='gift_reason',
            field=models.TextField(blank=True, help_text='Reason or note for giving this item as gift', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_gift',
            field=models.BooleanField(default=False, help_text='Mark this item as a gift (0 Naira income, only admin can set)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='original_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original selling price before marking as gift (for reporting)', max_digits=10, null=True),
        ),
    ]
