# Generated by Django 5.0.14 on 2026-02-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_sale_gift_reason_sale_is_gift_sale_original_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('failed_login', 'Failed Login Attempt'), ('product_create', 'Product Created'), ('product_update', 'Product Updated'), ('product_delete', 'Product Deleted'), ('product_view', 'Product Viewed'), ('sale_create', 'Sale Created'), ('sale_cancel', 'Sale Cancelled'), ('receipt_view', 'Receipt Viewed'), ('receipt_download', 'Receipt Downloaded'), ('receipt_email', 'Receipt Emailed'), ('customer_create', 'Customer Created'), ('customer_update', 'Customer Updated'), ('customer_delete', 'Customer Deleted'), ('transfer_create', 'Transfer Created'), ('transfer_update', 'Transfer Updated'), ('quantity_update', 'Quantity Updated'), ('config_update', 'Configuration Updated'), ('printer_config', 'Printer Configuration Changed'), ('report_view', 'Report Viewed'), ('report_download', 'Report Downloaded'), ('report_email', 'Report Emailed'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('backup_create', 'Backup Created'), ('backup_restore', 'Backup Restored'), ('settings_change', 'Settings Changed'), ('other', 'Other Action')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='action',
            field=models.CharField(choices=[('EDIT', 'Edit'), ('DELETE', 'Delete')], max_length=10),
        ),
    ]
