"""
Django settings for mystore project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =====================================
# SECURITY SETTINGS
# =====================================
# Load from environment variables for security
SECRET_KEY = config('DJANGO_SECRET_KEY', default='django-insecure-3h@@4#utmq-56*7@k755r6%hvki7rqqh0i5k*p4_e#*9-#hkq3')
DEBUG = config('DJANGO_DEBUG', default=True, cast=bool)
ALLOWED_HOSTS = config('DJANGO_ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    "crispy_forms",
    "crispy_bootstrap5",
    "widget_tweaks",
    'django_celery_beat',
    'django_celery_results',
    # OEM Reporting System
    'oem_reporting',
    'rest_framework',
    'rest_framework_simplejwt',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files efficiently
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'store.middleware.AccessControlMiddleware',
]

ROOT_URLCONF = 'mystore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'store.context_processors.user_permissions',
                'store.context_processors.store_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'mystore.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DB_ENGINE = config('DB_ENGINE', default='mssql')

# Configure OPTIONS based on database engine
if DB_ENGINE == 'django.db.backends.postgresql':
    # PostgreSQL configuration
    DB_OPTIONS = {
        'client_encoding': 'UTF8',
    }
    DB_PORT_DEFAULT = '5432'
elif DB_ENGINE == 'mssql':
    # MS SQL Server configuration
    DB_OPTIONS = {
        'driver': config('DB_DRIVER', default='ODBC Driver 17 for SQL Server'),
        'Encrypt': True,
        'TrustServerCertificate': True,
        'ATOMIC_REQUESTS': True
    }
    DB_PORT_DEFAULT = ''
else:
    DB_OPTIONS = {}
    DB_PORT_DEFAULT = ''

DATABASES = {
    'default': {
        'ENGINE': DB_ENGINE,
        'NAME': config('DB_NAME', default='Store'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='*3mb741101'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default=DB_PORT_DEFAULT),
        'OPTIONS': DB_OPTIONS,
        'CONN_MAX_AGE': 600 if DB_ENGINE == 'django.db.backends.postgresql' else 0,
    },
    # PythonAnywhere MySQL Database for OEM Reporting (COMMENTED OUT - Using PostgreSQL only)
    # 'oem_sync_db': {
    #     'ENGINE': config('CLOUD_DB_ENGINE', default='django.db.backends.mysql'),
    #     'NAME': config('CLOUD_DB_NAME', default='asoniguguru$Store'),
    #     'USER': config('CLOUD_DB_USER', default='asoniguguru'),
    #     'PASSWORD': config('CLOUD_DB_PASSWORD', default='*3mb741101'),
    #     'HOST': config('CLOUD_DB_HOST', default='asoniguguru.mysql.pythonanywhere-services.com'),
    #     'PORT': config('CLOUD_DB_PORT', default='3306'),
    #     'OPTIONS': {
    #         'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
    #         'charset': 'utf8mb4',
    #         'connect_timeout': 5,
    #     },
    #     'CONN_MAX_AGE': 600,
    #     'TEST': {
    #         'NAME': None,
    #     },
    # },
}
# Database router for OEM reporting models (COMMENTED OUT - Using PostgreSQL only)
# DATABASE_ROUTERS = ['oem_reporting.database_router.OEMSyncRouter']

# =====================================
# REST FRAMEWORK CONFIGURATION
# =====================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/hour',
        'user': '1000/day'
    }
}

# JWT Token Settings
from datetime import timedelta as jwt_timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': jwt_timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': jwt_timedelta(days=7),
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# ⚠️ IMPORTANT: Set your correct timezone for proper scheduling
TIME_ZONE = 'Africa/Lagos'  # Changed from UTC to Lagos timezone
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = config('STATIC_ROOT', default=os.path.join(BASE_DIR, 'static_root'))



SASS_PROCESSOR_ROOT = os.path.join(BASE_DIR, 'static', 'scss')
SASS_PROCESSOR_OUTPUT_DIR = 'css'

MEDIA_URL = '/media/'
MEDIA_ROOT = config('MEDIA_ROOT', default=os.path.join(BASE_DIR, 'media'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =====================================
# DAILY REPORT EMAIL CONFIGURATION
# =====================================

from datetime import timedelta

# Basic email settings - using environment variables
DAILY_REPORT_EMAIL = config('DAILY_REPORT_EMAIL', default='youngoni4u@gmail.com')
DAILY_REPORT_CC_EMAILS = config('DAILY_REPORT_CC_EMAILS', default='', cast=Csv())

# Email configuration - secured with environment variables
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='youngoni4u@gmail.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='vutx kuxl aiqq lowd')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='youngoni4u@gmail.com')

# =====================================
# REPORT CONFIGURATION (ADD THESE)
# =====================================

# Report generation settings
DAILY_REPORT_CONFIG = {
    'SEND_TIME': '11:00',  # 24-hour format
    'RETRY_ATTEMPTS': 3,
    'RETRY_DELAY': 600,  # seconds (10 minutes)
    'INCLUDE_ZERO_SALES_DAYS': True,  # Whether to send reports for days with no sales
    'ATTACHMENT_FORMATS': ['pdf', 'excel'],  # Available: pdf, excel, csv
    'MAX_EMAIL_SIZE': 25 * 1024 * 1024,  # 25MB max email size
}

# Report recipients configuration
DAILY_REPORT_RECIPIENTS = {
    'primary': [
        DAILY_REPORT_EMAIL,
    ],
    'cc': DAILY_REPORT_CC_EMAILS,
    'bcc': [],
}

# Report content configuration
DAILY_REPORT_CONTENT = {
    'include_summary': True,
    'include_item_breakdown': True,
    'include_payment_methods': True,
    'include_customer_details': True,
    'group_by_receipt': True,
    'show_discounts': True,
    'show_delivery_costs': True,
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'daily_reports_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'daily_reports.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'daily_reports': {
            'handlers': ['daily_reports_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'ERROR',  # Only show errors, not warnings
            'propagate': False,
        },
    },
}

logs_dir = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(logs_dir):
    os.makedirs(logs_dir)

# =====================================
# CELERY CONFIGURATION
# =====================================

REDIS_URL = config('REDIS_URL', default='redis://localhost:6379/0')

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE  # Uses 'Africa/Lagos'

# Use django_celery_beat database scheduler
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# =====================================
# CELERY BEAT SCHEDULE
# =====================================
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Database backup to flash drive - Daily at 11:00 AM
    'run-daily-backup': {
        'task': 'store.tasks.run_daily_backup_task',
        'schedule': crontab(hour=11, minute=0),  # 11:00 AM daily, Lagos time
        'options': {
            'expires': 7200,  # Expires after 2 hours if not executed
        }
    },
    # PythonAnywhere data sync - Every 30 minutes
    'sync-to-pythonanywhere-every-30-minutes': {
        'task': 'store.tasks.sync_to_pythonanywhere_task',
        'schedule': crontab(minute='*/30'),  # Every 30 minutes
        'options': {
            'expires': 1800,  # Task expires after 30 minutes if not executed
        }
    },
}
# =====================================
# CACHING (OPTIONAL - FOR PERFORMANCE)
# =====================================

# Simple cache configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutes
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Cache timeout for report data (in seconds)
REPORT_CACHE_TIMEOUT = 300  # 5 minutes

# =====================================
# DEVELOPMENT OVERRIDES
# =====================================

if DEBUG:
    DAILY_REPORT_CONFIG['RETRY_ATTEMPTS'] = 2
    DAILY_REPORT_CONFIG['RETRY_DELAY'] = 60  # 1 minute

    # 3. Enable more verbose logging
    LOGGING['loggers']['daily_reports']['level'] = 'DEBUG'

# =====================================
# SECURITY SETTINGS (FOR PRODUCTION)
# =====================================

# File upload settings for reports
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB


# Always protect these regardless of DEBUG mode
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 86400  # 24 hours